# Generated by Django 4.2 on 2023-04-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("selling_price", models.FloatField()),
                ("discounted_price", models.FloatField()),
                ("description", models.TextField()),
                ("composition", models.TextField(default="")),
                ("prodapp", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PP", "Panipuri"),
                            ("ND", "Noodles"),
                            ("MM", "Momos"),
                            ("LS", "Lassi"),
                            ("CH", "Chaas"),
                            ("CB", "Chole"),
                            ("GJ", "Gulabjamun"),
                            ("PS", "Pasta"),
                            ("IC", "Ice-Creams"),
                            ("MP", "Misalpav"),
                            ("RG", "Rasgulla"),
                            ("BR", "Brownie"),
                            ("MJ", "Mojito"),
                            ("SK", "Solkadi"),
                        ],
                        max_length=2,
                    ),
                ),
                ("product_image", models.ImageField(upload_to="product")),
            ],
        ),
    ]
