# Generated by Django 4.2 on 2023-04-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo1", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("ST", "Starters"),
                    ("MC", "Main Course"),
                    ("DS", "Dessert"),
                    ("DK", "Drinks"),
                ],
                max_length=2,
            ),
        ),
    ]
